package com.theaigames.boardgame;

import com.theaigames.game.player.AbstractPlayer;


/**
 * abstract class AbstractField
 * 
 * DO NOT EDIT THIS FILE
 * 
 * Extend this class with your main method.
 * 
 * @author Joost de Meij <developers@starapple.nl>
 */
public class AbstractField {
	private AbstractPlayer mOwner;
	private String mType;
	private String mPiece;
	private String mTag;
	
	public AbstractField() {
	}
	
	public void setOwner(AbstractPlayer owner) {
		mOwner = owner;
	}
	public void setType(String type) {
		mType = type;
	}
	public void setPiece(String piece) {
		mPiece = piece;
	}
	public void setTag(String tag) {
		mTag = tag;
	}
	
	public AbstractPlayer getOwner() {
		return mOwner;
	}
	public String getType() {
		return mType;
	}
	public String getPiece() {
		return mPiece;
	}
	public String getTag() {
		return mTag;
	}
	
}
